- id: '1606672479850'
  alias: Alarm Armed
  description: Shut garage doors, lock the door to garage and turn off TV
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode_alarm
    to: armed_away
  condition: []
  action:
  - device_id: 49c47010dfc55acbbdf71af225bedec8
    domain: lock
    entity_id: lock.mud_room_lock
    type: lock
  - device_id: fa0659c851465fa31dab8c05860cc895
    domain: cover
    entity_id: cover.left_garage_door
    type: close
  - device_id: f65020bcebb9e1a97728b22a47cba52d
    domain: cover
    entity_id: cover.right_garage_door
    type: close
  - service: notify.mobile_app_toms_iphone
    data:
      title: Alarm Armed
      message: What do you want to do?
      data:
        push:
          category: vacuum
  mode: single
- id: '1606672828264'
  alias: Alarm Disarmed
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode_alarm
    to: disarmed
  condition: []
  action:
  - device_id: 49c47010dfc55acbbdf71af225bedec8
    domain: lock
    entity_id: lock.mud_room_lock
    type: unlock
  mode: single
- id: '1606676673191'
  alias: Thermostats (20 miles moving away)
  description: Set thermostats to Eco if more than 20 miles away and traveling away
    from home.
  trigger:
  - platform: numeric_state
    entity_id: proximity.home
    above: '20'
  condition:
  - condition: state
    entity_id: proximity.home
    attribute: dir_of_travel
    state: away_from
  action:
  - device_id: 08a6dd4b35b484d1b40a2ecd10030df2
    domain: climate
    entity_id: climate.flex_room
    type: set_preset_mode
    preset_mode: eco
  - device_id: 015b691a363ef213cfde9c91ad3cab1e
    domain: climate
    entity_id: climate.bedroom
    type: set_preset_mode
    preset_mode: eco
  mode: single
- id: '1606676792936'
  alias: Thermostats (20 miles moving towards)
  description: Set thermostats to Eco if more than 20 miles away and traveling towards
    from home.
  trigger:
  - platform: numeric_state
    entity_id: proximity.home
    below: '20'
  condition:
  - condition: state
    entity_id: proximity.home
    state: towards
    attribute: dir_of_travel
  action:
  - device_id: 015b691a363ef213cfde9c91ad3cab1e
    domain: climate
    entity_id: climate.bedroom
    type: set_preset_mode
    preset_mode: none
  - device_id: 08a6dd4b35b484d1b40a2ecd10030df2
    domain: climate
    entity_id: climate.flex_room
    type: set_preset_mode
    preset_mode: none
  mode: single
- id: '1607443386474'
  alias: Reset Motion Sensors
  description: ''
  trigger:
  - platform: state
    to: 'on'
    for: 00:05:00
    entity_id:
    - binary_sensor.front_door_motion_sensor
    - binary_sensor.great_room_motion_sensor
    - binary_sensor.kitchen_motion_sensor
  condition: []
  action:
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: '{{ trigger.entity_id }}'
      state: 'off'
  mode: queued
  max: 10
- id: '1607449164931'
  alias: Auto-Home
  description: ''
  trigger:
  - platform: device
    device_id: a919f08b2260a5f05c4321713fe57e07
    domain: device_tracker
    entity_id: device_tracker.tom_s_iphone
    type: enters
    zone: zone.home
  - platform: device
    device_id: 07abf403cb31b012a75b9b2210f815a1
    domain: device_tracker
    entity_id: device_tracker.theresas_iphone
    type: enters
    zone: zone.home
  condition: []
  action:
  - device_id: 6cf7de2f629dae59e6d3a0b6f78c1881
    domain: alarm_control_panel
    entity_id: alarm_control_panel.abode_alarm
    type: disarm
    code: '0000'
  mode: single
- id: '1607638210964'
  alias: Reset Motion Sensors (Startup)
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay: 00:01:00
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: binary_sensor.front_door_motion_sensor
      state: 'off'
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: binary_sensor.great_room_motion_sensor
      state: 'off'
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: binary_sensor.kitchen_motion_sensor
      state: 'off'
  mode: single
- id: '1607901423295'
  alias: Notification Alarm Arm
  description: ''
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: ALARM_ARM
  condition: []
  action:
  - device_id: 6cf7de2f629dae59e6d3a0b6f78c1881
    domain: alarm_control_panel
    entity_id: alarm_control_panel.abode_alarm
    type: arm_away
  mode: single
- id: '1607968203974'
  alias: Doorbell Ring
  description: ''
  trigger:
  - platform: device
    device_id: 9d8105f724dc536601acaa2daf3cef79
    domain: nest
    type: camera_person
  - platform: device
    device_id: 9d8105f724dc536601acaa2daf3cef79
    domain: nest
    type: doorbell_chime
  condition: []
  action:
  - service: tts.google_translate_say
    data:
      entity_id: media_player.office_display
      message: Someone is at the front door
  - service: notify.alexa_media
    data:
      message: Someone is at the front door
      data:
        type: tts
      target:
      - media_player.kitchen_alexa
  - service: var.set
    entity_id: var.previous_cabinet_light_state
    data_template:
      value: '{{ states("light.cabinet") }}'
  - service: var.set
    entity_id: var.previous_cabinet_light_brightness
    data_template:
      value: '{{ state_attr("light.cabinet", "brightness") }}'
  - service: var.set
    entity_id: var.previous_cabinet_light_hs_color
    data_template:
      value: '{{ state_attr("light.cabinet", "hs_color") }}'
  - service: light.turn_on
    data:
      brightness: 255
      transition: 0
      hs_color:
      - 360
      - 100
      flash: short
    entity_id: light.cabinet
  - delay: 00:00:05
  - service_template: "{% if is_state('var.previous_cabinet_light_state', 'on') %}\n\
      \  light.turn_on\n{% else %}\n  light.turn_off\n{% endif %}\n"
    data_template:
      brightness: '{{ states("var.previous_cabinet_light_brightness")|int }}

        '
      hs_color: '{{ states("var.previous_cabinet_light_hs_color") }}

        '
    entity_id: light.cabinet
  - delay: 00:00:10
  mode: single
- id: '1607999948442'
  alias: Kitchen Motion Lights
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.basement_door_motion_sensor_occupancy
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: light.cabinet
      state: 'off'
    - condition: numeric_state
      entity_id: automation.kitchen_motion_lights
      attribute: current
      above: '0'
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.cabinet
  - wait_for_trigger:
    - platform: state
      from: 'on'
      to: 'off'
      entity_id: binary_sensor.basement_door_motion_sensor_occupancy
  - delay: 00:02:00
  - service: light.turn_off
    data: {}
    entity_id: light.cabinet
  mode: restart
- id: '1608858136491'
  alias: Kitchen iBeacon Test
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.mqtt_60cbab37_8f46_4482_9b89_27781ac02af6
    to: kitchen
  condition: []
  action:
  - service: notify.mobile_app_toms_iphone
    data:
      message: Entered kitchen
  mode: single
- alias: Set Default Theme
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: kibibit
    service: frontend.set_theme
  id: 5338138641074509ac3d115c3132d868
- id: '1617642446660'
  alias: Set Nest Motion Entities
  description: ''
  trigger:
  - platform: device
    device_id: 79442c3198ce3df321db20b7874d6285
    domain: nest
    type: camera_motion
  - platform: device
    device_id: 9d8105f724dc536601acaa2daf3cef79
    domain: nest
    type: camera_motion
  - platform: device
    device_id: b8c655b88ad70bf5a8c4e92f4d7d5ffc
    domain: nest
    type: camera_motion
  - platform: device
    device_id: b2f4cef4c127ec8f30d445e39dd7add5
    domain: nest
    type: camera_motion
  - platform: device
    device_id: 631237edbf1b66bf10461c63d27d037a
    domain: nest
    type: camera_motion
  - platform: device
    device_id: f608a75804749b060fc4274bb4bd9939
    domain: nest
    type: camera_motion
  condition: []
  action:
  - service: input_boolean.turn_on
    data_template:
      entity_id: "{% set deviceId = trigger.event | regex_findall_index(\"device_id=([0-9a-f]+?),\"\
        ) %}\n{% if deviceId == \"79442c3198ce3df321db20b7874d6285\" %}\n  input_boolean.motion_abels_room\n\
        {% elif deviceId == \"f608a75804749b060fc4274bb4bd9939\" %}\n  input_boolean.motion_backyard_camera\n\
        {% elif deviceId == \"9d8105f724dc536601acaa2daf3cef79\" %}\n  input_boolean.motion_front_door\n\
        {% elif deviceId == \"b8c655b88ad70bf5a8c4e92f4d7d5ffc\" %}\n  input_boolean.motion_kitchen\n\
        {% elif deviceId == \"b2f4cef4c127ec8f30d445e39dd7add5\" %}\n  input_boolean.motion_morning_room\n\
        {% elif deviceId == \"631237edbf1b66bf10461c63d27d037a\" %}\n  input_boolean.motion_nursery\n\
        {% endif %}\n"
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - service: input_boolean.turn_off
    data_template:
      entity_id: "{% set deviceId = trigger.event | regex_findall_index(\"device_id=([0-9a-f]+?),\"\
        ) %}\n{% if deviceId == \"79442c3198ce3df321db20b7874d6285\" %}\n  input_boolean.motion_abels_room\n\
        {% elif deviceId == \"f608a75804749b060fc4274bb4bd9939\" %}\n  input_boolean.motion_backyard_camera\n\
        {% elif deviceId == \"9d8105f724dc536601acaa2daf3cef79\" %}\n  input_boolean.motion_front_door\n\
        {% elif deviceId == \"b8c655b88ad70bf5a8c4e92f4d7d5ffc\" %}\n  input_boolean.motion_kitchen\n\
        {% elif deviceId == \"b2f4cef4c127ec8f30d445e39dd7add5\" %}\n  input_boolean.motion_morning_room\n\
        {% elif deviceId == \"631237edbf1b66bf10461c63d27d037a\" %}\n  input_boolean.motion_nursery\n\
        {% endif %}\n"
  mode: queued
  max: 10
- id: '1618875855459'
  alias: 'Tag scan: Toggle Mudroom Lock'
  description: ''
  trigger:
  - platform: event
    event_type: tag_scanned
    context:
      user_id:
      - 7e537ada4de44808a33c00cbf425c4e0
      - 9c546e5ab33f47fcbd2103594668aaaf
    event_data:
      tag_id: a8c94b61-8c2e-4c4e-83ac-12320c6a94ab
  condition: []
  action:
  - service_template: "{% if is_state('lock.mud_room_lock', 'locked') %}\n  lock.unlock\n\
      {% else %}\n  lock.lock\n{% endif %}\n"
    target:
      entity_id: lock.mud_room_lock
    data: {}
  mode: single
- id: '1618931661466'
  alias: 'Tag scan: Toggle Left Garage Door'
  description: ''
  trigger:
  - platform: event
    event_type: tag_scanned
    context:
      user_id:
      - 7e537ada4de44808a33c00cbf425c4e0
      - 9c546e5ab33f47fcbd2103594668aaaf
    event_data:
      tag_id: a8e180a9-678e-4725-9257-625425614d2a
  condition: []
  action:
  - service: cover.toggle
    target:
      entity_id: cover.left_garage_door
    data: {}
  mode: single
- id: '1618932628621'
  alias: 'Tag scan: Toggle Right Garage Door'
  description: ''
  trigger:
  - platform: event
    event_type: tag_scanned
    context:
      user_id:
      - 7e537ada4de44808a33c00cbf425c4e0
      - 9c546e5ab33f47fcbd2103594668aaaf
    event_data:
      tag_id: 3c9eae60-e72c-45e2-b4bc-8c1a92fc9820
  condition: []
  action:
  - service: cover.toggle
    data: {}
    target:
      entity_id: cover.right_garage_door
  mode: single
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  mode: queued
  max: 999
  trigger:
    platform: mqtt
    topic: shellies/announce
  action:
    service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
      shellyswitch25-3C6105E4C230:
        relay-0: light
        relay-1: light
        force_update_sensors: true
      shelly1-E8DB84ACA160:
        relay-0: light
        force_update_sensors: true
