- id: '1606672479850'
  alias: Alarm Armed
  description: Shut garage doors, lock the door to garage and turn off TV
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode_alarm
    to: armed_away
  condition: []
  action:
  - device_id: 49c47010dfc55acbbdf71af225bedec8
    domain: lock
    entity_id: lock.mud_room_lock
    type: lock
  - device_id: 785c6be41c4f044832af48da1a4914aa
    domain: cover
    entity_id: cover.left_garage_door
    type: close
  - device_id: facd77083527751232d4ca17bb6e89a6
    domain: cover
    entity_id: cover.right_garage_door
    type: close
  - service: notify.mobile_app_toms_iphone
    data:
      title: Alarm Armed
      message: What do you want to do?
      data:
        push:
          category: vacuum
  - service: media_player.play_media
    data:
      media_content_id: KEY_HOME
      media_content_type: send_key
    entity_id: media_player.samsung_tv_remote
  - delay: 00:00:03
  - service: media_player.turn_off
    data: {}
    entity_id: media_player.samsung_tv_remote
  mode: single
- id: '1606672828264'
  alias: Alarm Disarmed
  description: ''
  trigger:
  - platform: state
    entity_id: alarm_control_panel.abode_alarm
    to: disarmed
  condition: []
  action:
  - device_id: 49c47010dfc55acbbdf71af225bedec8
    domain: lock
    entity_id: lock.mud_room_lock
    type: unlock
  mode: single
- id: '1606674668151'
  alias: Sunrise Lights
  description: ''
  trigger:
  - platform: sun
    event: sunrise
  condition: []
  action:
  - type: turn_off
    device_id: 18077eac0791cd53cd1ce66a14220124
    entity_id: switch.porch_lights
    domain: switch
  - type: turn_off
    device_id: 5678b3ec46c6e5f666354d354df6a6f9
    entity_id: switch.driveway_lights
    domain: switch
  mode: single
- id: '1606674804175'
  alias: Sunset Lights
  description: ''
  trigger:
  - platform: sun
    event: sunset
  condition: []
  action:
  - type: turn_on
    device_id: 18077eac0791cd53cd1ce66a14220124
    entity_id: switch.porch_lights
    domain: switch
  - type: turn_on
    device_id: 5678b3ec46c6e5f666354d354df6a6f9
    entity_id: switch.driveway_lights
    domain: switch
  mode: single
- id: '1606676673191'
  alias: Thermostats (20 miles moving away)
  description: Set thermostats to Eco if more than 20 miles away and traveling away
    from home.
  trigger:
  - platform: numeric_state
    entity_id: proximity.home
    above: '20'
  condition:
  - condition: state
    entity_id: proximity.home
    attribute: dir_of_travel
    state: away_from
  action:
  - device_id: bcfa9d832e8fb3753b9c94cfa94e2536
    domain: climate
    entity_id: climate.bedroom
    type: set_preset_mode
    preset_mode: eco
  - device_id: f36a7d2c6689e95bf27b497e70af797f
    domain: climate
    entity_id: climate.flex_room
    type: set_preset_mode
    preset_mode: eco
  mode: single
- id: '1606676792936'
  alias: Thermostats (20 miles moving towards)
  description: Set thermostats to Eco if more than 20 miles away and traveling towards
    from home.
  trigger:
  - platform: numeric_state
    entity_id: proximity.home
    below: '20'
  condition:
  - condition: state
    entity_id: proximity.home
    state: towards
    attribute: dir_of_travel
  action:
  - device_id: bcfa9d832e8fb3753b9c94cfa94e2536
    domain: climate
    entity_id: climate.bedroom
    type: set_preset_mode
    preset_mode: none
  - device_id: f36a7d2c6689e95bf27b497e70af797f
    domain: climate
    entity_id: climate.flex_room
    type: set_preset_mode
    preset_mode: none
  mode: single
- id: '1607443386474'
  alias: Reset Motion Sensors
  description: ''
  trigger:
  - platform: state
    to: 'on'
    for: 00:10:00
    entity_id:
    - binary_sensor.front_door_motion_sensor
    - binary_sensor.great_room_motion_sensor
    - binary_sensor.kitchen_motion_sensor
  condition: []
  action:
  - service: python_script.set_state
    data:
      entity_id: '{{ trigger.entity_id }}'
      state: 'off'
  mode: parallel
  max: 10
- id: '1607449164931'
  alias: Auto-Home
  description: ''
  trigger:
  - platform: device
    device_id: d7d5a15b61df46c3940375a105d98d11
    domain: device_tracker
    entity_id: device_tracker.toms_iphone
    type: enters
    zone: zone.home
  - platform: device
    device_id: 07abf403cb31b012a75b9b2210f815a1
    domain: device_tracker
    entity_id: device_tracker.theresas_iphone
    type: enters
    zone: zone.home
  condition: []
  action:
  - device_id: 6cf7de2f629dae59e6d3a0b6f78c1881
    domain: alarm_control_panel
    entity_id: alarm_control_panel.abode_alarm
    type: disarm
    code: '0000'
  mode: single
- id: '1607638210964'
  alias: Reset Motion Sensors (Startup)
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay: 00:01:00
  - service: python_script.set_state
    data:
      entity_id: binary_sensor.front_door_motion_sensor
      state: 'off'
  - service: python_script.set_state
    data:
      entity_id: binary_sensor.great_room_motion_sensor
      state: 'off'
  - service: python_script.set_state
    data:
      entity_id: binary_sensor.kitchen_motion_sensor
      state: 'off'
  mode: single
- id: '1607894409563'
  alias: Notification Vacuum Main Floor
  description: ''
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: VACUUM_MAIN_FLOOR
  condition: []
  action:
  - service: vacuum.start
    entity_id: vacuum.greatroomroomba
    data: {}
  mode: single
- id: '1607896379577'
  alias: Notification Vacuum Great Room
  description: ''
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: VACUUM_GREAT_ROOM
  condition: []
  action:
  - service: vacuum.send_command
    data:
      command: start
      params:
        pmap_id: NW0eUDwfSAmv9dqz0ttnjQ
        user_pmapv_id: 201210T200858
        regions:
        - region_id: '9'
          type: rid
    entity_id: vacuum.greatroomroomba
  mode: single
- id: '1607900406169'
  alias: Notification Close Garage
  description: ''
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: GARAGE_CLOSE
  condition: []
  action:
  - device_id: 785c6be41c4f044832af48da1a4914aa
    domain: cover
    entity_id: cover.left_garage_door
    type: close
  - device_id: facd77083527751232d4ca17bb6e89a6
    domain: cover
    entity_id: cover.right_garage_door
    type: close
  mode: single
- id: '1607901423295'
  alias: Notification Alarm Arm
  description: ''
  trigger:
  - platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: ALARM_ARM
  condition: []
  action:
  - device_id: 6cf7de2f629dae59e6d3a0b6f78c1881
    domain: alarm_control_panel
    entity_id: alarm_control_panel.abode_alarm
    type: arm_away
  mode: single
