- id: '1606676673191'
  alias: Thermostats (20 miles moving away)
  description: Set thermostats to Eco if more than 20 miles away and traveling away
    from home.
  trigger:
  - platform: numeric_state
    entity_id: proximity.home
    above: '20'
  condition:
  - condition: state
    entity_id: proximity.home
    attribute: dir_of_travel
    state: away_from
  action:
  - device_id: 08a6dd4b35b484d1b40a2ecd10030df2
    domain: climate
    entity_id: climate.flex_room
    type: set_preset_mode
    preset_mode: eco
  - device_id: 015b691a363ef213cfde9c91ad3cab1e
    domain: climate
    entity_id: climate.bedroom
    type: set_preset_mode
    preset_mode: eco
  mode: single
- id: '1606676792936'
  alias: Thermostats (20 miles moving towards)
  description: Set thermostats to Eco if more than 20 miles away and traveling towards
    from home.
  trigger:
  - platform: numeric_state
    entity_id: proximity.home
    below: '20'
  condition:
  - condition: state
    entity_id: proximity.home
    state: towards
    attribute: dir_of_travel
  action:
  - device_id: 015b691a363ef213cfde9c91ad3cab1e
    domain: climate
    entity_id: climate.bedroom
    type: set_preset_mode
    preset_mode: none
  - device_id: 08a6dd4b35b484d1b40a2ecd10030df2
    domain: climate
    entity_id: climate.flex_room
    type: set_preset_mode
    preset_mode: none
  mode: single
- id: '1607443386474'
  alias: Reset Motion Sensors
  description: ''
  trigger:
  - platform: state
    to: 'on'
    for: 00:05:00
    entity_id:
    - binary_sensor.front_door_motion_sensor
    - binary_sensor.great_room_motion_sensor
    - binary_sensor.kitchen_motion_sensor
  condition: []
  action:
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: '{{ trigger.entity_id }}'
      state: 'off'
  mode: queued
  max: 10
- id: '1607638210964'
  alias: Reset Motion Sensors (Startup)
  description: ''
  trigger:
  - platform: homeassistant
    event: start
  condition: []
  action:
  - delay: 00:01:00
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: binary_sensor.front_door_motion_sensor
      state: 'off'
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: binary_sensor.great_room_motion_sensor
      state: 'off'
  - service: python_script.hass_entities
    data:
      action: set_state
      entity_id: binary_sensor.kitchen_motion_sensor
      state: 'off'
  mode: single
- id: '1607999948442'
  alias: Kitchen Motion Lights
  description: ''
  trigger:
  - platform: state
    from: 'off'
    to: 'on'
    entity_id: binary_sensor.basement_door_motion_sensor_occupancy
  condition:
  - condition: or
    conditions:
    - condition: state
      entity_id: light.cabinet
      state: 'off'
    - condition: numeric_state
      entity_id: automation.kitchen_motion_lights
      attribute: current
      above: '0'
  action:
  - service: light.turn_on
    data: {}
    entity_id: light.cabinet
  - wait_for_trigger:
    - platform: state
      from: 'on'
      to: 'off'
      entity_id: binary_sensor.basement_door_motion_sensor_occupancy
  - delay: 00:02:00
  - service: light.turn_off
    data: {}
    entity_id: light.cabinet
  mode: restart
- id: '1608858136491'
  alias: Kitchen iBeacon Test
  description: ''
  trigger:
  - platform: state
    entity_id: device_tracker.mqtt_60cbab37_8f46_4482_9b89_27781ac02af6
    to: kitchen
  condition: []
  action:
  - service: notify.mobile_app_toms_iphone
    data:
      message: Entered kitchen
  mode: single
- alias: Set Default Theme
  description: ''
  trigger:
  - event: start
    platform: homeassistant
  condition: []
  action:
  - data:
      name: kibibit
    service: frontend.set_theme
  id: 5338138641074509ac3d115c3132d868
- id: '1617642446660'
  alias: Set Nest Motion Entities
  description: ''
  trigger:
  - platform: device
    device_id: 79442c3198ce3df321db20b7874d6285
    domain: nest
    type: camera_motion
  - platform: device
    device_id: 9d8105f724dc536601acaa2daf3cef79
    domain: nest
    type: camera_motion
  - platform: device
    device_id: b8c655b88ad70bf5a8c4e92f4d7d5ffc
    domain: nest
    type: camera_motion
  - platform: device
    device_id: b2f4cef4c127ec8f30d445e39dd7add5
    domain: nest
    type: camera_motion
  - platform: device
    device_id: 631237edbf1b66bf10461c63d27d037a
    domain: nest
    type: camera_motion
  - platform: device
    device_id: f608a75804749b060fc4274bb4bd9939
    domain: nest
    type: camera_motion
  condition: []
  action:
  - service: input_boolean.turn_on
    data_template:
      entity_id: "{% set deviceId = trigger.event | regex_findall_index(\"device_id=([0-9a-f]+?),\"\
        ) %}\n{% if deviceId == \"79442c3198ce3df321db20b7874d6285\" %}\n  input_boolean.motion_abels_room\n\
        {% elif deviceId == \"f608a75804749b060fc4274bb4bd9939\" %}\n  input_boolean.motion_backyard_camera\n\
        {% elif deviceId == \"9d8105f724dc536601acaa2daf3cef79\" %}\n  input_boolean.motion_front_door\n\
        {% elif deviceId == \"b8c655b88ad70bf5a8c4e92f4d7d5ffc\" %}\n  input_boolean.motion_reeves_room\n\
        {% elif deviceId == \"b2f4cef4c127ec8f30d445e39dd7add5\" %}\n  input_boolean.motion_morning_room\n\
        {% elif deviceId == \"631237edbf1b66bf10461c63d27d037a\" %}\n  input_boolean.motion_nursery\n\
        {% endif %}\n"
  - delay:
      hours: 0
      minutes: 0
      seconds: 20
      milliseconds: 0
  - service: input_boolean.turn_off
    data_template:
      entity_id: "{% set deviceId = trigger.event | regex_findall_index(\"device_id=([0-9a-f]+?),\"\
        ) %}\n{% if deviceId == \"79442c3198ce3df321db20b7874d6285\" %}\n  input_boolean.motion_abels_room\n\
        {% elif deviceId == \"f608a75804749b060fc4274bb4bd9939\" %}\n  input_boolean.motion_backyard_camera\n\
        {% elif deviceId == \"9d8105f724dc536601acaa2daf3cef79\" %}\n  input_boolean.motion_front_door\n\
        {% elif deviceId == \"b8c655b88ad70bf5a8c4e92f4d7d5ffc\" %}\n  input_boolean.motion_reeves_room\n\
        {% elif deviceId == \"b2f4cef4c127ec8f30d445e39dd7add5\" %}\n  input_boolean.motion_morning_room\n\
        {% elif deviceId == \"631237edbf1b66bf10461c63d27d037a\" %}\n  input_boolean.motion_nursery\n\
        {% endif %}\n"
  mode: queued
  max: 10
- id: '1618875855459'
  alias: 'Tag scan: Toggle Mudroom Lock'
  description: ''
  trigger:
  - platform: event
    event_type: tag_scanned
    context:
      user_id:
      - 7e537ada4de44808a33c00cbf425c4e0
      - 9c546e5ab33f47fcbd2103594668aaaf
    event_data:
      tag_id: a8c94b61-8c2e-4c4e-83ac-12320c6a94ab
  condition: []
  action:
  - service_template: "{% if is_state('lock.mud_room_lock', 'locked') %}\n  lock.unlock\n\
      {% else %}\n  lock.lock\n{% endif %}\n"
    target:
      entity_id: lock.mud_room_lock
    data: {}
  mode: single
- id: '1618931661466'
  alias: 'Tag scan: Toggle Left Garage Door'
  description: ''
  trigger:
  - platform: event
    event_type: tag_scanned
    context:
      user_id:
      - 7e537ada4de44808a33c00cbf425c4e0
      - 9c546e5ab33f47fcbd2103594668aaaf
    event_data:
      tag_id: a8e180a9-678e-4725-9257-625425614d2a
  condition: []
  action:
  - service: cover.toggle
    target:
      entity_id: cover.left_garage_door
    data: {}
  mode: single
- id: '1618932628621'
  alias: 'Tag scan: Toggle Right Garage Door'
  description: ''
  trigger:
  - platform: event
    event_type: tag_scanned
    context:
      user_id:
      - 7e537ada4de44808a33c00cbf425c4e0
      - 9c546e5ab33f47fcbd2103594668aaaf
    event_data:
      tag_id: 3c9eae60-e72c-45e2-b4bc-8c1a92fc9820
  condition: []
  action:
  - service: cover.toggle
    data: {}
    target:
      entity_id: cover.right_garage_door
  mode: single
- id: shellies_announce
  alias: Shellies Announce
  trigger:
  - platform: homeassistant
    event: start
  - platform: time_pattern
    hours: /1
  action:
    service: mqtt.publish
    data:
      topic: shellies/command
      payload: announce
- id: shellies_discovery
  alias: Shellies Discovery
  trigger:
  - platform: mqtt
    topic: shellies/announce
  action:
  - service: python_script.shellies_discovery
    data:
      id: '{{ trigger.payload_json.id }}'
      mac: '{{ trigger.payload_json.mac }}'
      fw_ver: '{{ trigger.payload_json.fw_ver }}'
      model: '{{ trigger.payload_json.model }}'
      mode: '{{ trigger.payload_json.mode | default }}'
      host: '{{ trigger.payload_json.ip }}'
      shellyswitch25-3C6105E4C230:
        relay-0: light
        relay-1: light
        force_update_sensors: true
      shelly1-E8DB84ACA160:
        relay-0: light
        force_update_sensors: true
      shelly1-3C6105E3A4C2:
        relay-0: light
        force_update_sensors: true
      shelly1-3C6105E3A7C9:
        relay-0: light
        force_update_sensors: true
  mode: queued
  max: 999
- id: '1644036755398'
  alias: Basement Projector Wake-on-LAN
  trigger:
  - platform: webostv.turn_on
    entity_id: media_player.basement_projector
  action:
  - service: wake_on_lan.send_magic_packet
    data:
      mac: B0:37:95:01:2B:92
      broadcast_address: 192.168.0.255
- id: '1645034312500'
  alias: Dryer Complete
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.dryer_dry_completed
    from: 'off'
    to: 'on'
  condition: []
  action:
  - service: notify.alexa_media
    data:
      message: The dryer is done. You better get folding.
      target:
      - media_player.kitchen_alexa
      data:
        type: tts
  mode: single
- id: '1646407771689'
  alias: New version availabile
  description: ''
  trigger:
  - platform: state
    entity_id: update.home_assistant_core_update
    from: 'off'
    to: 'on'
  - platform: homeassistant
    event: start
  - platform: time
    at: '12:00:00'
  condition: []
  action:
  - delay:
      hours: 0
      minutes: 1
      seconds: 0
      milliseconds: 0
  - condition: state
    entity_id: update.home_assistant_core_update
    state: 'on'
  - service: notify.mobile_app_toms_iphone
    data:
      title: HA v{{ states('sensor.home_assistant_website') }} is now available
      message: Currently running v{{ states('sensor.current_version') }}
      data:
        actions:
        - action: RELEASE_NOTES
          title: Open Release Notes
          uri: '{{ state_attr(''sensor.home_assistant_website'', ''release_notes'')
            }}'
        - action: UPDATE
          title: Update Version
          uri: /config/dashboard
  mode: single
