- platform: template
  sensors:
    # Abode battery sensors
    mud_room_keypad_battery:
      device_class: battery
      friendly_name_template: >-
        {{ state_attr("binary_sensor.mud_room_keypad", "friendly_name") }} Battery
      value_template: >-
        {% if state_attr("binary_sensor.mud_room_keypad", "battery_low") %}
          low
        {% else %}
          full
        {% endif %}
      icon_template: >-
        {% if state_attr("binary_sensor.mud_room_keypad", "battery_low") %}
          mdi:battery-alert
        {% else %}
          mdi:battery
        {% endif %}

    bedroom_keypad_battery:
      device_class: battery
      friendly_name_template: >-
        {{ state_attr("binary_sensor.bedroom_keypad", "friendly_name") }} Battery
      value_template: >-
        {% if state_attr("binary_sensor.bedroom_keypad", "battery_low") %}
          low
        {% else %}
          full
        {% endif %}
      icon_template: >-
        {% if state_attr("binary_sensor.bedroom_keypad", "battery_low") %}
          mdi:battery-alert
        {% else %}
          mdi:battery
        {% endif %}