- platform: template
  switches:
    # A switch that mirrors switch.adguard_protection
    # Echo doesn't like when you say "turn off ad guard protection"
    ad_filter:
      friendly_name: "Ad Filter"
      unique_id: template_switch_ad_filter
      value_template: "{{ is_state('switch.adguard_protection', 'on') }}"
      turn_on:
        service: switch.turn_on
        target:
          entity_id: switch.adguard_protection
      turn_off:
        service: switch.turn_off
        target:
          entity_id: switch.adguard_protection
