binary_sensor:
   # On if a garage door is open at night
  - unique_id: garage_open_at_night
    state: >-
      {{ is_state("sun.sun", "below_horizon") and (is_state("cover.left_garage_door", "open") or is_state("cover.right_garage_door", "open")) }}
    attributes:
      friendly_name: "Garage doors"

  # On if the alarm isn't set and we are 20 miles from home
  - unique_id: alarm_not_set
    state: >-
      {{ states("proximity.home")|int > 20 and is_state("alarm_control_panel.abode_alarm", "disarmed") }}
    attributes:
      friendly_name: "Alarm"

  # On if the alarm isn't set and we are 20 miles from home
  - unique_id: office_ups_low_voltage
    state: >-
      {{ states("sensor.apc_input_voltage")|int < 100 }}
    attributes:
      friendly_name: "Office UPS low voltage"
