sensor:
  - name: Tom's Location
    unique_id: toms_location_template_sensor
    state: >
      {% if(is_state("device_tracker.toms_iphone","home") and not is_state("sensor.tom_s_iphone_presence","not_home")) %}
        {{ states("sensor.tom_s_iphone_presence") }}
      {% else %}
        {{ states("device_tracker.toms_iphone") }}
      {% endif %}